- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2022022809535251560000000c.cbbd5xznkze8.us-east-1.rds.amazonaws.com" 
    login_user: "taiwo"
    login_password: "password"
    name: wordpressdb
    collation: utf8_general_ci
    encoding: utf8
    state: present


- name: Input wordpress credentials
  ansible.builtin.replace:
    path: /var/www/html/wp-config.php 
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^localhost', replace: "terraform-2022022809535251560000000c.cbbd5xznkze8.us-east-1.rds.amazonaws.com" }
    - { regexp: '^username_here', replace: "taiwo" }
    - { regexp: '^database_name_here', replace: "wordpressdb" }
    - { regexp: '^password_here', replace: "password" }
