- name: Install PyMySQL
  pip:
    name: pymysql
    state: present
    
- name: create database
  community.mysql.mysql_db:
    login_host: "terraform-2022022809535251560000000c.cbbd5xznkze8.us-east-1.rds.amazonaws.com"
    login_user: "taiwo"
    login_password: "password"
    name: toolingdb
    collation: utf8_general_ci
    encoding: utf8
    state: present

- name: Input tooling credentials
  ansible.builtin.replace:
    path: /var/www/html/functions.php
    regexp: "{{ item.regexp }}"
    replace: "{{ item.replace }}"
  loop:
    - { regexp: '^mysql.tooling.svc.cluster.local', replace: "terraform-2022022809535251560000000c.cbbd5xznkze8.us-east-1.rds.amazonaws.com" }
    - { regexp: '^admin', replace: "taiwo" }
    - { regexp: '^tooling', replace: "toolingdb" }
    - { regexp: '^admin', replace: "password" }

